apiVersion: apps/v1
kind: Deployment # Resource kind
metadata:
  name: evote-frontend-app-deployment
  labels:
    app: evote-frontend-app
spec:
  replicas: 2 # Number of replicas
  selector:
    matchLabels:
      app: evote-frontend-app
  template:
    metadata:
      labels:
        app: evote-frontend-app
    spec:
      containers:
      - name: evote-frontend-app
        image: rajithafernando/evote-frontend-app
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: evote-frontend-app-service
spec:
  selector:
    app.kubernetes.io/name: evote-frontend-app
  ports:
    - protocol: TCP
      port: 3000 # The port that service is running in the cluster
      targetPort: 3000 # The port expoursed by the service
  type : NodePort
